language: ruby
bundler_args: --without development
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
env:
  # TODO: 0.8 is enough on Linux, but 2 seems needed for Travis/OSX
  - LISTEN_TESTS_DEFAULT_LAG=2
sudo: false
