language: ruby
bundler_args: --without development --path vendor/bundle
before_install:
  - gem update --system
  - gem install bundler
  - gem update bundler
  - bundle install
script:
  - bundle exec rspec spec/acceptance/listen_spec.rb:231
rvm:
  #- 2.2
  #- 2.3
  #- 2.4
  #- 2.5
  #- ruby-head
  - jruby-head
  #- rbx-3
  - jruby-9.2.0.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
  exclude:
    - rvm: 2.3.4
      os: osx
    - rvm: 2.4.1
      os: osx
    - rvm: jruby-head
      os: osx
    - rvm: rbx-3
      os: osx
  fast_finish: true
os:
  - linux
  - osx
osx_image: xcode7.1
env:
  # TODO: 0.8 is enough on Linux, but 2 seems needed for Travis/OSX
  - LISTEN_TESTS_DEFAULT_LAG=2
sudo: false
cache: bundler
